let str1 = "abc";
let str2 = "def";
println("str1=",str1,"  str2=",str2);
println("str1+str2=",str1+str2);

let a = 1;
let b = 2;
let c = 3;
println("a=",a,"  b=",b,"  c=",c);
println("a+b=",a+b);
println("a-b=",a-b);
println("a/b=",a/b);
println("a*b=",a*b);
println("a<b=",a<b);
println("a>b=",a>b);
println("(a==b)=",a==b);

let flag = false;
let flag2 = true;
println("flag=", flag, "  flag2=",flag2);
println("!flag=",!flag,"  !flag2=",!flag2);
